### PR TITLE
Update zhCN.lua

### PR DESCRIPTION
**Pull request by T3rdW**

### CODE REVIEW

**Comment by Slivo-fr** [comment]
Hey, thanks for contributing !

Isn't this redondant with https://github.com/Slivo-fr/TranqRotate/pull/28 ?
It's been merged in v1.3 but not release yet

Please use develop as target for your merge requests please :)

**Comment by T3rdW** [comment]
Sorry, I didn't notice this message

**Comment by Slivo-fr** [comment]
@T3rdW Hey mate, there are new translation keys on the v1.4.0 branch. I'm going to push the alpha to beta in few days, do you want to take a look at translation before it happens ?

**Comment by T3rdW** [comment]
@Slivo-fr ok!

**Pull request closed without merging**
