### PR TITLE
Bugfix/disable whisper channel annouce options

### PR DESCRIPTION
**Pull request by Slivo-fr**

### CODE REVIEW

**Comment by violatorno** [comment]
How can I issues a pull request on #23 to get the file changes to release?
Tested it out in 2 raids with multiple hunters, works well, good job.

**Comment by Slivo-fr** [comment]
Hi !

I did not understand your question, could you please rephrase ?
The changes have been merged on develop branch and will be part of the next release, I still have some feature I want to work on before pushing this release out

Thanks for your support :)

**Comment by violatorno** [comment]
Hi :)
I tested the changes out with our raid, 5-6 hunters.
It worked out well, does exactly what I asked for. 
I was asking for a pull from devel to master/release so that it also is updated on https://www.curseforge.com/wow/addons/tranqrotate
Maybe commit to master branch is the correct sentence?
But as your still working on some additionals they just have to be patient and wait :)

**Comment by Slivo-fr** [comment]
Merging into master is likely what you meant, but this won't update on curste unless I push an update manually :)

You may want to join the discord, beta releases are likely to be available there before anywhere else

**Pull request merged**
