### PR TITLE
Update ruRU.lua

### PR DESCRIPTION
**Pull request by ivan-rabtsevich**
more comprehensive translation. Fixed errors and typos

### CODE REVIEW

**Comment by Slivo-fr** [comment]
Hey mate, thanks for your help ! :)

I was waiting for beta channel to update the description of new features but I through you would like to avoid another merge request so I updated it !

Could you please take a look at SETTING_GENERAL_DESC key again please ? :)

**Comment by ivan-rabtsevich** [comment]
> Hey mate, thanks for your help ! :)
> 
> I was waiting for beta channel to update the description of new features but I through you would like to avoid another merge request so I updated it !
> 
> Could you please take a look at SETTING_GENERAL_DESC key again please ? :)

Hey! Sure! I updated SETTING_GENERAL_DESC key.

**Comment by Slivo-fr** [comment]
Thanks ! 

Your branch still have some conflict with the target, could you please solve them so I can merge ?

**Comment by ivan-rabtsevich** [comment]
> Thanks !
> 
> Your branch still have some conflict with the target, could you please solve them so I can merge ?

Done! :)

**Comment by Slivo-fr** [comment]
Wonderful, thanks! Merging right now :)

**Pull request merged**
