### PR TITLE
Update zhCN.lua

### PR DESCRIPTION
**Pull request by T3rdW**

### CODE REVIEW

**Comment by Slivo-fr** [comment]
Thanks for contributing mate ! :D

**Comment by T3rdW** [comment]
It was nothing~ :D

**Comment by Slivo-fr** [comment]
Not that I don't understand all of this ... but I don't !
Should I wait for some changes or are the merged translations fine ?

**Comment by T3rdW** [comment]
@Slivo-fr 
I resubmitted a branch and found a more suitable translation. You can merge that branch. Thank you!
#51

**Pull request merged**
